name: "Build Release"

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Choose release type (release or pre-release)"
        required: true
        default: "release"
        type: choice
        options:
          - pre-release
          - release

permissions:
  contents: write

jobs:
  # test:  # 注释掉整个测试任务
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.15.1
  #     - run: npm ci
  #     - name: Start Xvfb
  #       run: |
  #         sudo apt-get install -y xvfb
  #         Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  #         echo "DISPLAY=:99" >> $GITHUB_ENV
  #     - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
      - run: npm ci
      - run: npx vsce package --out "cline-${{ github.ref_name }}.vsix"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: "*.vsix"
          generate_release_notes: true
          prerelease: ${{ github.event.inputs.release-type == 'pre-release' }}
