name: "Build Release"

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Choose release type (release or pre-release)"
        required: true
        default: "release"
        type: choice
        options:
          - pre-release
          - release

permissions:
  contents: write  # 仅需写入权限（用于创建 Release）

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
      - run: npm ci
      - run: npm test  # 直接运行测试

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
      - run: npm ci
      - run: npx vsce package --out "cline-${{ github.ref_name }}.vsix"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: "*.vsix"
          generate_release_notes: true
          prerelease: ${{ github.event.inputs.release-type == 'pre-release' }}
